name: Release

on:
  workflow_dispatch:
  push:
    branches: master
  repository_dispatch:
    types:
      - webhook
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build environment
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Logging into dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push image
        run: |
          docker buildx build --push \
            --tag ${{ github.repository }}:latest \
            --platform linux/amd64,linux/arm64 .
